const U=1,B=0;
const METRICS={
 motor:{name:'Motor Control & Capacity',desc:'Movement ownership, repeated capacity, early landing tolerance and bulletproofing flags.',streams:['Single-Leg Control','Capacity','Landing Prep','Bulletproofing Overlay'],items:[
  ['sl_squat','Single-Leg Squat to 90°',20,'reps @ 40 bpm','gte',U],['split_squat','Split Squat',20,'reps @ 40 bpm','gte',U],['sl_bridge','Single-Leg Hamstring Bridge',20,'reps @ 40 bpm','gte',U],['sl_calf','Single-Leg Calf Raise',25,'reps @ 60 bpm','gte',U],['box_landing_lsi','Box Landing Peak Landing Force LSI',80,'%','gte',B]
 ]},
 strength:{name:'Strength & Hypertrophy',desc:'Local torque, hypertrophy and global force capacity.',streams:['Quad','Hamstring','Calf / Soleus','Hip Strength','Bilateral Lift','Single-Leg Strength'],items:[
  ['knee_ext','Knee Extension Strength',3.3,'Nm/kg','gte',U],['knee_flex','Knee Flexion Strength',2.0,'Nm/kg','gte',U],['seated_pf','Seated Plantarflexion Strength',200,'% BW','gte',U],['hip_abd','Hip Abduction Strength',2.0,'Nm/kg','gte',U],['sl_depth','5RM Single-Leg Squat Depth Average',105,'° knee flexion','gte',U],['front_squat','Front Squat 1RM',1.5,'× BW','gte',B],['deadlift','Deadlift 1RM',2.25,'× BW','gte',B],['split_load','Split Squat 5RM',0.5,'× BW','gte',U]
 ]},
 power:{name:'Power & RFD',desc:'Double-leg and single-leg CMJ kinetics and kinematics.',streams:['Jump Power','Quad Speed','Hip Extension Power','Landing Kinematics'],items:[
  ['dl_cmj','DL CMJ Height',38,'cm','gte',B],['dl_impulse','DL CMJ Concentric Impulse',2.6,'N·s/kg','gte',B],['dl_p2','DL CMJ P2 Impulse',45,'% total','gte',B],['dl_ecc','DL CMJ Eccentric Impulse',0.5,'N·s/kg','gte',B],['dl_power','DL CMJ Peak Power',52,'W/kg','gte',B],['dl_land','DL CMJ Peak Landing Force',[35,55],'N/kg','range',B],
  ['sl_cmj','SL CMJ Height',17.1,'cm','gte',U],['sl_impulse','SL CMJ Concentric Impulse',1.35,'N·s/kg','gte',U],['sl_p2','SL CMJ P2 Contribution',45,'%','gte',U],['sl_ecc','SL CMJ Eccentric Impulse',0.35,'N·s/kg','gte',U],['sl_land','SL CMJ Peak Landing Force',[22,28],'N/kg','range',U],
  ['cmj_knee_depth','CMJ Knee Flexion Depth',[65,90],'°','range',B],['cmj_hip_depth','CMJ Hip Flexion Depth',[50,80],'°','range',B],['land_knee_initial','Initial Landing Knee Flexion',[15,30],'°','range',B],['land_knee_peak','Peak Landing Knee Flexion',[45,70],'°','range',B],['land_hip','Landing Hip Flexion',[30,60],'°','range',B]
 ]},
 reactive:{name:'Reactive Strength',desc:'Fast force acceptance and rebound. RSI, GCT, hopping and stiffness.',streams:['Pogos','Drop Jump','SL Drop Jump','Hopping / Bounds'],items:[
  ['dldj_rsi','DL Drop Jump RSI',1.3,'','gte',B],['dldj_gct','DL Drop Jump GCT',0.25,'s','lt',B],['sldj_rsi','SL Drop Jump RSI',0.52,'','gte',U],['sldj_gct','SL Drop Jump GCT',0.30,'s','lt',U],['triple_dist','Triple Crossover Hop Distance',650,'cm','gte',U],['triple_lsi','Triple Crossover Hop LSI',92,'%','gte',B]
 ]},
 running:{name:'Linear Running',desc:'High-speed mechanics: pelvis, trunk, hip adduction and exposure progression.',streams:['Running Mechanics','Hip Lock','Acceleration','Max Velocity Exposure'],items:[
  ['pelvic_tilt','Peak Pelvic Tilt',16,'°','lte',U],['pelvic_exc','Peak Pelvic Excursion',11,'°','lte',U],['trunk_angle','Peak Trunk Angle',11,'°','lte',U],['pelvic_ob_run','Peak Pelvic Obliquity',5,'°','gte',U],['hip_add','Peak Hip Adduction',13,'°','lte',U],['trunk_lat','Peak Trunk Lateral Flexion',12,'°','lte',U]
 ]},
 cod:{name:'Change of Direction',desc:'Deceleration, cutting and sport-direction force redirection.',streams:['Deceleration','45° Cut','90° Cut','Reactive Cut','Sport Chaos'],items:[
  ['pen_asym','Penultimate Foot Contact Asymmetry',10,'%','lt',B],['pen_time','Penultimate Foot Contact Time',0.46,'s','lt',U],['cod_knee','Peak Knee Flexion',[37,59],'°','range',U],['cod_hip','Peak Hip Flexion',[22,49],'°','range',U],['cod_trunk','Peak Trunk Flexion',5,'°','gt',U],['cod_pelvis','Peak Pelvic Obliquity',17,'°','gt',U]
 ]},
 gates:{name:'Entry / Return Gates',desc:'Linear running, COD, full training and return to play gate criteria.',streams:['Return to Run Gate','COD Gate','Full Training Gate','RTP Gate'],items:[
  ['rtr_ext','Run Gate Knee Extension',2.31,'Nm/kg','gte',U],['rtr_flex','Run Gate Knee Flexion',1.4,'Nm/kg','gte',U],['rtr_pf','Run Gate Seated PF',140,'% BW','gte',U],['rtr_slcmj','Run Gate SLCMJ Height',12,'cm','gte',U],['rtr_sldj','Run Gate SLDJ RSI',0.36,'','gte',U],
  ['cod_ext','COD Gate Knee Extension',2.64,'Nm/kg','gte',U],['cod_flex','COD Gate Knee Flexion',1.6,'Nm/kg','gte',U],['cod_pf','COD Gate Seated PF',160,'% BW','gte',U],['cod_abd','COD Gate Hip Abduction',1.6,'Nm/kg','gte',U],['cod_slcmj','COD Gate SLCMJ Height',13.7,'cm','gte',U],['cod_sldj','COD Gate SLDJ RSI',0.42,'','gte',U],
  ['full_ext','Full Training Knee Extension',3.0,'Nm/kg','gte',U],['full_flex','Full Training Knee Flexion',1.8,'Nm/kg','gte',U],['full_pf','Full Training Seated PF',180,'% BW','gte',U],['full_abd','Full Training Hip Abduction',1.8,'Nm/kg','gte',U],['full_slcmj','Full Training SLCMJ Height',15.4,'cm','gte',U],['full_sldj','Full Training SLDJ RSI',0.47,'','gte',U],
  ['acl_rsi','ACL-RSI',60,'','gte',B],['rtp_ext','RTP Knee Extension',3.3,'Nm/kg','gte',U],['rtp_flex','RTP Knee Flexion',2.0,'Nm/kg','gte',U],['rtp_pf','RTP Seated PF',200,'% BW','gte',U],['rtp_abd','RTP Hip Abduction',2.0,'Nm/kg','gte',U],['rtp_slcmj','RTP SLCMJ Height',17.1,'cm','gte',U],['rtp_sldj','RTP SLDJ RSI',0.52,'','gte',U]
 ]}
};
const STAGE_KEYS=Object.keys(METRICS);
function blankSession(date='2026-05-01'){const s={date};Object.values(METRICS).flatMap(x=>x.items).forEach(m=>s[m[0]]=m[5]?{left:'',right:''}:'' );return s;}
function demoSession(){return {date:'2026-05-01',sl_squat:{left:24,right:18},split_squat:{left:23,right:22},sl_bridge:{left:22,right:20},sl_calf:{left:28,right:21},box_landing_lsi:84,knee_ext:{left:3.4,right:2.72},knee_flex:{left:2.05,right:1.62},seated_pf:{left:210,right:165},hip_abd:{left:2.05,right:1.72},sl_depth:{left:110,right:101},front_squat:.95,deadlift:1.55,split_load:{left:.48,right:.36},dl_cmj:31.5,dl_impulse:2.35,dl_p2:42,dl_ecc:.43,dl_power:47,dl_land:41,sl_cmj:{left:18.2,right:13.8},sl_impulse:{left:1.45,right:1.10},sl_p2:{left:47,right:39},sl_ecc:{left:.38,right:.28},sl_land:{left:25,right:20},cmj_knee_depth:62,cmj_hip_depth:48,land_knee_initial:12,land_knee_peak:42,land_hip:28,dldj_rsi:1.08,dldj_gct:.27,sldj_rsi:{left:.58,right:.41},sldj_gct:{left:.27,right:.33},triple_dist:{left:680,right:590},triple_lsi:88,pelvic_tilt:{left:14,right:17},pelvic_exc:{left:9,right:12},trunk_angle:{left:10,right:10},pelvic_ob_run:{left:6,right:4},hip_add:{left:11,right:14},trunk_lat:{left:9,right:10},pen_asym:14,pen_time:{left:.44,right:.49},cod_knee:{left:43,right:35},cod_hip:{left:32,right:20},cod_trunk:{left:8,right:6},cod_pelvis:{left:20,right:15},rtr_ext:{left:3.4,right:2.72},rtr_flex:{left:2.05,right:1.62},rtr_pf:{left:210,right:165},rtr_slcmj:{left:18.2,right:13.8},rtr_sldj:{left:.58,right:.41},cod_ext:{left:3.4,right:2.72},cod_flex:{left:2.05,right:1.62},cod_pf:{left:210,right:165},cod_abd:{left:2.05,right:1.72},cod_slcmj:{left:18.2,right:13.8},cod_sldj:{left:.58,right:.41},full_ext:{left:3.4,right:2.72},full_flex:{left:2.05,right:1.62},full_pf:{left:210,right:165},full_abd:{left:2.05,right:1.72},full_slcmj:{left:18.2,right:13.8},full_sldj:{left:.58,right:.41},acl_rsi:54,rtp_ext:{left:3.4,right:2.72},rtp_flex:{left:2.05,right:1.62},rtp_pf:{left:210,right:165},rtp_abd:{left:2.05,right:1.72},rtp_slcmj:{left:18.2,right:13.8},rtp_sldj:{left:.58,right:.41}}}
const DEFAULT={athletes:[{name:'Sample ACLR Athlete',side:'right',sessions:[demoSession()]}]};
let data=JSON.parse(localStorage.hpLLfull||JSON.stringify(DEFAULT)),ai=0,si=0,stage='motor';const $=x=>document.getElementById(x);function athlete(){return data.athletes[ai]}function sess(){return athlete().sessions[si]}function save(){localStorage.hpLLfull=JSON.stringify(data)}function val(m,s=sess(),a=athlete()){const x=s[m[0]];return m[5]&&typeof x==='object'?Number(x[a.side]):Number(x)}function lsi(m,s=sess()){const x=s[m[0]];if(!m[5]||!x||typeof x!=='object'||x.left===''||x.right==='')return null;const L=Number(x.left),R=Number(x.right);if(!L||!R)return null;return Math.round(Math.min(L,R)/Math.max(L,R)*100)}function status(m){const v=val(m);if(v===''||v==null||Number.isNaN(v))return ['fail','Missing',0];let t=m[2],d=m[4],pass=false,ratio=0;if(d==='gte'){pass=v>=t;ratio=v/t}if(d==='gt'){pass=v>t;ratio=v/t}if(d==='lte'){pass=v<=t;ratio=t/v}if(d==='lt'){pass=v<t;ratio=t/v}if(d==='range'){pass=v>=t[0]&&v<=t[1];let mid=(t[0]+t[1])/2;ratio=pass?1:1-Math.min(Math.abs(v-mid)/mid,1)}let L=lsi(m),sym=!m[5]||L===null||L>=92;if(pass&&sym)return ['pass','Pass',100];if(pass&&!sym)return ['watch','LSI watch',70];if(ratio>=.85)return ['watch','Watch',70];return ['fail','Needs work',Math.max(0,Math.round(ratio*60))]}function score(key){let arr=METRICS[key].items.map(m=>status(m)[2]);return Math.round(arr.reduce((a,b)=>a+b,0)/arr.length)}function overall(){let arr=STAGE_KEYS.map(k=>score(k));return Math.round(arr.reduce((a,b)=>a+b,0)/arr.length)}function target(m){return m[4]==='range'?`${m[2][0]}–${m[2][1]} ${m[3]}`:`${m[4].includes('gt')?'≥':'<'} ${m[2]} ${m[3]}`}function setVal(k,side,v){let s=sess();if(side){s[k]=s[k]&&typeof s[k]==='object'?s[k]:{left:'',right:''};s[k][side]=v===''?'':Number(v)}else s[k]=v===''?'':Number(v);save();render()}function allDeficits(){return STAGE_KEYS.flatMap(k=>METRICS[k].items.map(m=>({m,stage:METRICS[k].name,v:val(m),l:lsi(m),st:status(m)}))).filter(x=>x.st[0]!=='pass').sort((a,b)=>a.st[2]-b.st[2])}
function render(){let a=athlete(),s=sess(),M=METRICS[stage],o=overall();$('ath').innerHTML=data.athletes.map((x,i)=>`<option value=${i}>${x.name}</option>`).join('');$('ath').value=ai;$('side').value=a.side;$('session').innerHTML=a.sessions.map((x,i)=>`<option value=${i}>${x.date}</option>`).join('');$('session').value=si;$('meta').textContent=`${a.sessions.length} session(s) · Current: ${s.date}`;$('title').textContent=M.name;$('desc').textContent=M.desc;$('overall').textContent=o+'%';$('overalltxt').textContent=o>=85?'Ready profile':o>=70?'Developing profile':'Priority deficits';$('nav').innerHTML=STAGE_KEYS.map(k=>`<button class='${k===stage?'active':''}' onclick="stage='${k}';render()"><span>${METRICS[k].name}</span><b>${score(k)}%</b></button>`).join('');$('map').innerHTML=STAGE_KEYS.map(k=>`<div class=panel onclick="stage='${k}';render()"><b>${METRICS[k].name}</b><br>${score(k)}%</div>`).join('');$('bars').innerHTML=M.streams.map((x,i)=>`<div>${x}</div><div class=chart style='height:20px'><div style='height:20px;width:${90-i*12}%;background:#08aad0;border-radius:10px'></div></div>`).join('');$('streams').innerHTML=M.streams.map(x=>`<div class=panel>${x}</div>`).join('');$('metrics').innerHTML=M.items.map(m=>{let st=status(m),x=s[m[0]],L=lsi(m);let inputs=m[5]?`<div class=lr><label><small>Left</small><input value='${x?.left??''}' onchange="setVal('${m[0]}','left',this.value)"></label><label><small>Right</small><input value='${x?.right??''}' onchange="setVal('${m[0]}','right',this.value)"></label></div><p>Target side (${a.side}): <b>${val(m)||'--'}</b> ${m[3]} · LSI: <b>${L??'--'}%</b></p>`:`<input value='${x??''}' onchange="setVal('${m[0]}',null,this.value)">`;return `<div class=metric><h3>${m[1]} <span class='pill ${st[0]}'>${st[1]}</span></h3><p>Target: <b>${target(m)}</b></p>${inputs}</div>`}).join('');let d=allDeficits().slice(0,8);$('priorities').innerHTML=d.map(x=>`<li><b>${x.m[1]}</b> (${x.stage}) — ${x.m[5]?a.side+' ':''}${x.v||'missing'} ${x.m[3]}${x.l?`, LSI ${x.l}%`:''}; target ${target(x.m)}</li>`).join('')||'<li>All listed targets passed.</li>';$('trendMetric').innerHTML=Object.values(METRICS).flatMap(x=>x.items).map(m=>`<option value='${m[0]}'>${m[1]}</option>`).join('');$('chart').innerHTML='Trend chart uses saved testing sessions; duplicate sessions, edit values, then compare.';$('summary').value=`${a.name}\nSide: ${a.side}\nSession: ${s.date}\nOverall readiness: ${o}%\n\nTop priorities:\n${d.slice(0,6).map((x,i)=>`${i+1}. ${x.m[1]}: ${x.m[5]?a.side+' ':''}${x.v||'missing'} ${x.m[3]}${x.l?`, LSI ${x.l}%`:''} vs ${target(x.m)}`).join('\n')}`;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tabpage').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active')});}
window.onload=()=>{$('ath').onchange=e=>{ai=+e.target.value;si=0;render()};$('side').onchange=e=>{athlete().side=e.target.value;save();render()};$('session').onchange=e=>{si=+e.target.value;render()};$('newAth').onclick=()=>{let name=prompt('Athlete name?')||'New Athlete';data.athletes.push({name,side:'right',sessions:[blankSession()]});ai=data.athletes.length-1;si=0;save();render()};$('delAth').onclick=()=>{if(data.athletes.length>1&&confirm('Delete athlete?')){data.athletes.splice(ai,1);ai=0;si=0;save();render()}};$('newSess').onclick=()=>{let date=prompt('Session date? YYYY-MM-DD')||new Date().toISOString().slice(0,10);athlete().sessions.push(blankSession(date));si=athlete().sessions.length-1;save();render()};$('dupSess').onclick=()=>{let n=JSON.parse(JSON.stringify(sess()));n.date=prompt('New session date? YYYY-MM-DD')||new Date().toISOString().slice(0,10);athlete().sessions.push(n);si=athlete().sessions.length-1;save();render()};$('reset').onclick=()=>{localStorage.hpLLfull=JSON.stringify(DEFAULT);data=JSON.parse(localStorage.hpLLfull);ai=0;si=0;render()};$('copy').onclick=()=>navigator.clipboard.writeText($('summary').value);$('export').onclick=()=>{let b=new Blob([JSON.stringify(athlete(),null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=athlete().name.replaceAll(' ','_')+'.json';a.click()};$('import').onchange=e=>{let f=e.target.files[0],r=new FileReader();r.onload=()=>{data.athletes.push(JSON.parse(r.result));ai=data.athletes.length-1;si=0;save();render()};r.readAsText(f)};render()};